\subsubsection{Судоку}

Я также переписал пример с Судоку (\ref{sudoku_SMT}) для KLEE:

\lstinputlisting[numbers=left]{puzzles/sudoku/KLEE/klee_sudoku_or1.c}

Запустим:

\begin{lstlisting}
% clang -emit-llvm -c -g klee_sudoku_or1.c
...

\$ time klee klee_sudoku_or1.bc
KLEE: output directory is "/home/klee/klee-out-98"
KLEE: WARNING: undefined reference to function: klee_assert
KLEE: WARNING ONCE: calling external: klee_assert(0)
KLEE: ERROR: /home/klee/klee_sudoku_or1.c:93: failed external call: klee_assert
KLEE: NOTE: now ignoring this error at this location

KLEE: done: total instructions = 7512
KLEE: done: completed paths = 161
KLEE: done: generated tests = 161

real    3m44.111s
user    3m43.319s
sys     0m0.951s
\end{lstlisting}

Это работает медленнее (на моем ноутбуке Intel Core i3-3110M 2.4GHz) в сравнении с решением на Z3Py (\ref{sudoku_SMT}).

Но ответ верный:

\begin{lstlisting}
% ls klee-last | grep err
test000161.external.err

% ktest-tool --write-ints klee-last/test000161.ktest
ktest file : 'klee-last/test000161.ktest'
args       : ['klee_sudoku_or1.bc']
num objects: 1
object    0: name: b'cells'
object    0: size: 81
object    0: data: b'\x01\x04\x05\x03\x02\x07\x06\t\x08\x08\x03\t\x06\x05\x04\x01\x02\x07\x06\x07\x02\t\x01\x08\x05\x04\x03\x04\t\x06\x01\x08\x05\x03\x07\x02\x02\x01\x08\x04\x07\x03\t\x05\x06\x07\x05\x03\x02\t\x06\x04\x08\x01\x03\x06\x07\x05\x04\x02\x08\x01\t\t\x08\x04\x07\x06\x01\x02\x03\x05\x05\x02\x01\x08\x03\t\x07\x06\x04'
\end{lstlisting}

Символ \TT{\textbackslash{}t} в Си/Си++ имеет код 9,
а KLEE выводит массив байт как строку в Си/Си++, так что он показывает некоторые значения в таком виде.
Мы может просто помнить, что здесь 9 во всех местах, где мы видим \TT{\textbackslash{}t}.
Решение, хотя и не отформатировано должным образом, тем не мнее, корректно.

Кстати, в строках 42 и 43 вы можете увидеть, как мы говорим KLEE, что все элементы массива должны быть в некоторых
пределах.
Если закомментируем эти строки, получим это:

\begin{lstlisting}
% time klee klee_sudoku_or1.bc
KLEE: output directory is "/home/klee/klee-out-100"
KLEE: WARNING: undefined reference to function: klee_assert
KLEE: ERROR: /home/klee/klee_sudoku_or1.c:51: overshift error
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/klee/klee_sudoku_or1.c:51: overshift error
KLEE: NOTE: now ignoring this error at this location
KLEE: ERROR: /home/klee/klee_sudoku_or1.c:51: overshift error
KLEE: NOTE: now ignoring this error at this location
...
\end{lstlisting}

KLEE предупреждает нас, что значение сдвига на строке 51 слишком большое.
Действительно, KLEE может пробовать все значения байт вплоть до 255 (0xFF), что, в свою очередь, здесь бессмысленно,
и может быть симптомом ошибки, так что KLEE предупреждает об этом.

Снова попробуем использовать \TT{klee\_assume()}:

\lstinputlisting{puzzles/sudoku/KLEE/klee_sudoku_or2.c}

\begin{lstlisting}
% time klee klee_sudoku_or2.bc
KLEE: output directory is "/home/klee/klee-out-99"
KLEE: WARNING: undefined reference to function: klee_assert
KLEE: WARNING ONCE: calling external: klee_assert(0)
KLEE: ERROR: /home/klee/klee_sudoku_or2.c:93: failed external call: klee_assert
KLEE: NOTE: now ignoring this error at this location

KLEE: done: total instructions = 7119
KLEE: done: completed paths = 1
KLEE: done: generated tests = 1

real    0m35.312s
user    0m34.945s
sys     0m0.318s
\end{lstlisting}

Это работает намного быстрее: наверное, KLEE работает с этой \textit{intrinsic} специальным образом.
И, как мы видим, только один путь был найден (тот, который нам действительно интересен) вместо 161.

Но это всё еще намного медленнее, чем решение на Z3Py.

